setx -m PATH "%PATH%;%%ANT_HOME%%\bin;%%CYGWIN_HOME%%\bin;%%FLEX_HOME%%\bin;%%MAVEN_HOME%%\bin;%%PHP_HOME%%\;%%PEAR_HOME%%\"
mklink /J "%USERPROFILE%\AppData\Local\Apps" "%MYPROGRAMFILES%\ClickOnce"
mklink /J "%MYPROGRAMFILES% (x86)\Cygwin"      "%CYGWIN_HOME%"
mklink /J "%MYPROGRAMFILES% (x86)\Flex"        "%FLEX_HOME%"
mklink /J "%USERPROFILE%\.dia"        "%HOME%\.dia"
mklink /J "%USERPROFILE%\.eclipse"    "%HOME%\.eclipse"
mklink /J "%USERPROFILE%\.m2"         "%HOME%\.m2"
mklink /J "%USERPROFILE%\.ssh"        "%HOME%\.ssh"
mklink /J "%USERPROFILE%\.subversion" "%HOME%\.subversion"
mklink   "%USERPROFILE%\.gitconfig"  "%HOME%\.gitconfig"
